/*
 * Batch Processing Service API
 *
 * An API for managing batch processing jobs.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type JobsIdGet200Response struct {

	// Current status of the job.
	Status string `json:"status,omitempty"`

	// The result of the job.
	Result string `json:"result,omitempty"`
}
