/*
 * Batch Processing Service API
 *
 * An API for managing batch processing jobs.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type JobsPostRequest struct {

	// The type of task to perform.
	TaskType string `json:"taskType,omitempty"`

	// The input data for the job.
	InputData string `json:"inputData,omitempty"`
}
